repaint_delay 8
input_delay 2 
enable_audio_bell no
visual_bell_duration 0.0
copy_on_select yes

# >>> window >>>
hide_window_decorations yes
include                 kanagawa.conf
enabled_layouts         splits,stack,tall

remember_window_size    no
initial_window_width    110c
initial_window_height   30c

tab_bar_style           separator
tab_separator           " | "
tab_title_template      "[{index}]  {title[:18]}"
# <<< window <<<

# >>> cursor & font >>>
cursor_trail 10
cursor_trail_start_threshold 0
shell_integration no-cursor
cursor_trail_decay 0.01 0.15
cursor_shape            block
cursor_blink_interval 0.5
cursor_stop_blinking_after 0

font_family             IosevkaNerdFontMono
font_size               14.0
# <<< cursor & font <<<

# >>> keymaps >>>
map ctrl+shift+v        paste_from_clipboard
map ctrl+v              paste_from_clipboard
map alt+shift+d         launch --location=split --cwd=current
map ctrl+t              new_tab_with_cwd
map ctrl+p              previous_tab
map ctrl+n              next_tab
map ctrl+1              goto_tab 1
map ctrl+2              goto_tab 2
map ctrl+3              goto_tab 3
map ctrl+4              goto_tab 4
map ctrl+5              goto_tab 5
map f11                 toggle_fullscreen
map ctrl+h              neighboring_window left
map ctrl+j              neighboring_window down
map ctrl+k              neighboring_window up
map ctrl+l              neighboring_window right
map ctrl+shift+w        close_window
# <<< keymaps <<<
